server:
  port: 8082

spring:
  application:
    name: trace-api
  jpa:
    hibernate:
      ddl-auto: create-drop
  data:
    mongodb:
      uri: mongodb://localhost:27017/tracedata
  rabbitmq:
    username: guest
    password: guest
    port: '5672'
    host: localhost
